### ISSUE TITLE
Runtime error 216 at 0000000002F6D883

### ISSUE THREAD

**Issue by ottworks** [twxyz/BinAural-3D-plugin#2]
I tried to load this into FL studio x64 and it crashed. On the instances where I've gotten it to work, it just fills up the spectrum either +  or - and eats all my CPU. I'm on Windows 10.

**Comment by twoz** [comment]
Sorry, but without any more details I can't really help You (some FL studio dump or log would be ideal). This seems like a very weird issue not related to the plugin itself, because it's tested in other hosts on Win10 x64. Do You have any other DAW you can test it with? Also, that 216 error seems like a common issue for FL studio on a virus infected PC so I would try to rule that out first.
