### ISSUE TITLE
Giltchs in audio

### ISSUE THREAD

**Issue by Bk8** [twxyz/BinAural-3D-plugin#3]
I'm not sure why but when start moving the position of the source continuously, noise start to appear it sounds like vinyl noise. Do you know why I have the same problem in one of my plugins.

**Comment by twoz** [comment]
This is due to the waveform discontinuities that happen when changing the impulse response of a filter running with Overlap-Add/Save algorithm.

I have finally got around to fix it. I've chosen simple output time-domain crossfading which seem to work fine - in short, for each ear/channel, there are 2 filters, one with the updated impulse response, and their output is summed and cross-faded.

This imposes almost double the processing time, but can be easily optimized for example with some conditional logic which I plan to do at some point in the future.

**Comment by twoz** [comment]
Fixed with dd8c44b.
